//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meami.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Order Code Field is Required")]
        public string OrderCode { get; set; }
        [Required(ErrorMessage = "Customer Name Field is Required")]
        public Nullable<int> CustomerId { get; set; }
        [Required(ErrorMessage = "Product Name Field is Required")]
        public Nullable<int> ProductId { get; set; }
        [Required(ErrorMessage = "Product Count Field is Required")]
        public Nullable<int> ProductCount { get; set; }
    }
}
